name: "Docker-Container bauen"
description: "Baut einen Docker-Container und nutzt dafür eigene Standardwerte."
author: "c't"

inputs:
  registry_url:
    description: "URL der Docker Registry, ohne Slash am Ende."
    required: false
    default: "docker.pkg.github.com"

  registry_username:
    description: "Benutzername, mit dem sich an der Registry angemeldet wird."
    required: false
    default: "publisher"
  
  registry_password:
    description: "Passwort / Token, mit dem sich an der Registry angemeldet wird."
    required: true
  
  image_name:
    description: "Name des Docker-Images."
    required: true
  
  image_tag:
    description: "Tag des Docker-Images."
    required: false
    default: "latest"

runs:
  using: "docker"
  image: "Dockerfile"
