#!/bin/sh -l

FULL_IMAGE_NAME=${INPUT_REGISTRY_URL}/${GITHUB_REPOSITORY}/${INPUT_IMAGE_NAME}:${INPUT_IMAGE_TAG}

echo ${INPUT_REGISTRY_PASSWORD} | docker login -u ${INPUT_REGISTRY_USERNAME} --password-stdin ${INPUT_REGISTRY_URL}
docker build --tag ${FULL_IMAGE_NAME} .
docker push ${FULL_IMAGE_NAME}